from __future__ import annotations

from datetime import datetime
from typing import Protocol

from domain.publishing.models import (
    PlatformCapabilityV1,
    PublicationReceiptV1,
    PublicationV1,
    ScheduleV1,
)


class ScheduleRepositoryPort(Protocol):
    async def create(self, schedule: ScheduleV1) -> ScheduleV1: ...
    async def get(self, schedule_id: str) -> ScheduleV1 | None: ...
    async def list_due(self, now: datetime, limit: int = 100) -> list[ScheduleV1]: ...
    async def list_window(self, start_at: datetime, end_at: datetime) -> list[ScheduleV1]: ...
    async def list_for_approvals(self, approval_ids: list[str]) -> list[ScheduleV1]: ...
    async def cancel(self, schedule_id: str, now: datetime) -> ScheduleV1 | None: ...
    async def mark_dispatched(self, schedule_id: str, now: datetime) -> ScheduleV1 | None: ...
    async def mark_completed(self, schedule_id: str, now: datetime) -> ScheduleV1 | None: ...
    async def mark_failed(self, schedule_id: str, now: datetime, reason: str) -> ScheduleV1 | None: ...


class PublicationRepositoryPort(Protocol):
    async def create(self, publication: PublicationV1) -> PublicationV1: ...
    async def get(self, publication_id: str) -> PublicationV1 | None: ...
    async def get_by_idempotency_key(self, key: str) -> PublicationV1 | None: ...
    async def claim(self, publication_id: str, *, attempt_id: str, now: datetime) -> tuple[str, PublicationV1 | None]: ...
    async def mark_published(self, publication_id: str, *, attempt_id: str, receipt: PublicationReceiptV1, now: datetime) -> PublicationV1 | None: ...
    async def mark_failed_safe(self, publication_id: str, *, attempt_id: str, reason: str, now: datetime) -> PublicationV1 | None: ...
    async def mark_reconciliation_required(
        self,
        publication_id: str,
        *,
        attempt_id: str | None,
        reason: str,
        now: datetime,
        external_post_id: str | None = None,
        external_asset_ids: tuple[str, ...] = (),
    ) -> PublicationV1 | None: ...
    async def resolve_reconciliation_published(self, publication_id: str, *, receipt: PublicationReceiptV1, now: datetime) -> PublicationV1 | None: ...
    async def resolve_reconciliation_failed_safe(self, publication_id: str, *, reason: str, now: datetime) -> PublicationV1 | None: ...
    async def list_window(self, start_at: datetime, end_at: datetime) -> list[PublicationV1]: ...
    async def list_for_schedules(self, schedule_ids: list[str]) -> list[PublicationV1]: ...


class ConnectionRepositoryPort(Protocol):
    async def get_linkedin(self) -> dict | None: ...
    async def safe_status(self) -> dict: ...


class PlatformAdapterPort(Protocol):
    async def capabilities(self, connection: dict) -> PlatformCapabilityV1: ...
    async def publish(self, prepared, connection: dict) -> PublicationReceiptV1: ...
    async def reconcile(self, publication: PublicationV1, connection: dict) -> PublicationReceiptV1 | None: ...
