from typing import Protocol

from domain.profiles.models import Profile, ProfileInferenceProposal, ProfileSetup, ProfileVersion


class ProfileAnalyzerPort(Protocol):
    def propose(self, setup: ProfileSetup) -> ProfileInferenceProposal: ...


class ProfileRepositoryPort(Protocol):
    async def list_profiles(self) -> list[Profile]: ...
    async def get_profile(self, profile_id: str) -> Profile | None: ...
    async def get_version(self, profile_id: str, version: int) -> ProfileVersion | None: ...
    async def create(self, profile: Profile, version: ProfileVersion) -> None: ...
    async def append_version(self, profile: Profile, version: ProfileVersion, expected_version: int) -> bool: ...
